### PR TITLE
Delete old elections

### PR DESCRIPTION
**Pull request by MattConrad**
This is an initial version of an old election deleter.

It just provides an endpoint that calls a cloud function that runs the deletes. It doesn't provide a scheduler. Anything that can ping the endpoint will work as a scheduler. I would probably use Zapier.

This adds a "created" property to newly created elections. Elections without "created" (e.g. older ones) will be untouched by this delete routine. Currently set to delete elections more than 14 days old.

The cloud functions are almost a project within the regular project. It's a little weird. Some new lines in .gitignore.

### CODE REVIEW

**Comment by MattConrad** [comment]
This is related to https://github.com/damonblack/rcv-sim/issues/3

**Comment by damonblack** [comment]
This is great! I think we should merge, poke some old timestamps in to existing elections by hand, and see if it works. When we get it where we want, we can blow away the existing data and reset.

**Comment by MattConrad** [comment]
This has been "lightly tested" along the lines you describe (although I was lazy and usually used 1 for "created"). Should be good, but some more testing won't hurt.

I had thought the pull request would give you a nice diff of the total differences, and not all my scratchwork commits individually, sorry about that. Sounds like you sorted it out though.

**Review by damonblack — APPROVED** [review]
I can definitely see a need to turn this feature off, either on a per-file, or per-user basis.

**Comment by MattConrad** [comment]
Added #25 for adding the saveMe flag or whatever.

**Pull request merged**
